EXECUTABLE	:= interac-atomic
CUFILES_sm_13 := interac-atomic.cu

################################################################################
# Rules and targets

include ../../../common/common.mk
